# Generated by Django 5.2.4 on 2025-07-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Prova', max_length=200)),
                ('disciplina', models.CharField(max_length=100)),
                ('quantidade_questoes', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('questoes_ids', models.TextField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='cadastro.professor')),
            ],
            options={
                'verbose_name': 'Prova',
                'verbose_name_plural': 'Provas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='GabaritoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas_corretas', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('prova', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gabarito', to='cadastro.prova')),
            ],
            options={
                'verbose_name': 'Gabarito da Prova',
                'verbose_name_plural': 'Gabaritos das Provas',
            },
        ),
        migrations.CreateModel(
            name='ResultadoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas_aluno', models.TextField()),
                ('acertos', models.IntegerField()),
                ('total_questoes', models.IntegerField()),
                ('nota_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='cadastro.aluno')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='cadastro.prova')),
            ],
            options={
                'verbose_name': 'Resultado do Aluno',
                'verbose_name_plural': 'Resultados dos Alunos',
                'ordering': ['-data_realizacao'],
                'unique_together': {('aluno', 'prova')},
            },
        ),
    ]
